administrator/urls.py
from django.conf.urls import url
from administrator import views
from django.contrib.auth import views as auth_views

app_name = 'administrator'


urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^add-news/$', views.add_news, name='add-news'),
    url(r'^view-news/$', views.view_news, name='view-news'),
    url(r'^edit-news/(?P<pk>[0-9]+)/', views.UpdateNews.as_view(), name='update-news'),
    url(r'^delete-news/(?P<pk>[0-9]+)/', views.delete_news, name='delete-news'),
    url(r'^add-event/$', views.add_event, name='add-event'),
    url(r'^view-events/$', views.view_events, name='view-events'),
    url(r'^edit-event/(?P<pk>[0-9]+)/', views.EventUpdate.as_view(), name='update-event'),
    url(r'^delete-event/(?P<pk>[0-9]+)/', views.delete_event, name='delete-event'),
    url(r'^add-teacher/$', views.add_teacher, name='add-teacher'),
    url(r'^view-teachers/$', views.view_teachers, name='view-teachers'),
    url(r'^edit-teacher/(?P<pk>[0-9]+)/', views.TeacherUpdate.as_view(), name='update-teacher'),
    url(r'^delete-teacher/(?P<pk>[0-9]+)/', views.delete_teacher, name='delete-teacher'),
    url(r'^add-executive/$', views.add_executive, name='add-executive'),
    url(r'^view-executives/$', views.view_executives, name='view-executives'),
    url(r'^edit-executive/(?P<pk>[0-9]+)/', views.ExecutiveUpdate.as_view(), name='update-executive'),
    url(r'^delete-executive/(?P<pk>[0-9]+)/', views.delete_executive, name='delete-executive'),
    url(r'^profile/$', views.view_profile, name='profile'),
    url(r'^profile-update/$', views.update_profile, name='update-profile'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, 
    {'next_page': '/administrator/login/'}, name='logout'),
    
]

main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    # url(r'^$', views.index, name='index')
]

school/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^sysadmin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'administrator/', include('administrator.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

administrator/models.py
from django.db import models

# Create your models here.

administrator/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import User

from main.models import Event, News, Teacher, Executive, Profile


class EventForm(forms.ModelForm):
    event_date = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.DateInput(format = '%d-%m-%y'))
    class Meta:
        model = Event
        fields = [
            'event_title', 'event_description', 'event_image',
            'event_details', 'event_date', 'event_time',
        ]


class NewsForm(forms.ModelForm):

    class Meta:
        model = News
        fields = [
            'news_title', 'news_description',
            'news_image_1', 'news_image_2', 'news_image_3', 'news_detail',
        ]


class TeacherForm(forms.ModelForm):

    class Meta:
        model = Teacher
        fields = '__all__'
        exclude = ['teacher_status']


class ExecutiveForm(forms.ModelForm):

    class Meta:
        model = Executive
        fields = '__all__'


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['birth_date', 'picture', 'location', 'website', 'phone', 'occupation']

administrator/views.py
""" administrator/views.py file CRUD for my school information management."""
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import UpdateView

from main.models import Event, News, Teacher, Executive
from administrator.forms import (
    EventForm, NewsForm, TeacherForm,
    ExecutiveForm, UserForm, ProfileForm
)



# ==================================================================================================================================
# News CRUD
# ==================================================================================================================================

@login_required(login_url='/administrator/login')
def index(request):
    """Dashboard for logged in user."""
    event = Event.objects.filter(
        event_status='published').order_by('-date_modified')[:3]
    news = News .objects.filter(
        news_status='published').order_by('-date_modified')[:3]
    all_news = News.objects.filter(news_status='published')
    all_events = Event.objects.filter(event_status='published')
    all_teachers = Teacher.objects.all()
    all_executives = Executive.objects.all()
    return render(
        request, 'school/dashboard.html', {
            'event': event, 'news': news,
            'events': all_events, 'all_news': all_news,
            'teachers': all_teachers, 'executives': all_executives
        }
    )

@login_required(login_url='/administrator/login')
def add_news(request):
    """function for adding news."""
    if request.method == 'POST':
        form = NewsForm(request.POST, request.FILES)
        if form.is_valid():
            news = form.save(commit=False)
            news.news_author = User.objects.get(username=request.user)
            news.save()
            messages.success(
                request, 'you have successfully added an event await system administrator approval', extra_tags='alert')
            return redirect('administrator:view-events')
    else:
        form = NewsForm()

    return render(request, 'school/add-news.html', {'form': form})


@login_required(login_url='/administrator/login')
def view_news(request):
    """View all news that have been published."""
    news = News.objects.all().order_by('-date_modified')
    return render(request, 'school/view-news.html', {'news': news})


class UpdateNews(LoginRequiredMixin, UpdateView):
    form_class = NewsForm
    template_name = 'school/add-news.html'
    model = Event

    def get_object(self, *args, **kwargs):
        obj = get_object_or_404(News, pk=self.kwargs['pk'])
        return obj

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request,
            'News updated successfully', extra_tags='alert'
        )
        return redirect('administrator:view-news')



def delete_news(request, pk):
    """function to delete a single news."""
    instance = get_object_or_404(News, pk=pk)
    instance.delete()
    messages.success(request, instance.news_title +
                  ' has been deleted successfully')
    return redirect('administrator:view-events')

# ================================================================================================================================
# Events CRUD
# ==================================================================================================================================

@login_required(login_url='/administrator/login')
def add_event(request):
    """function for adding a single event."""
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.event_author = User.objects.get(username=request.user)
            event.save()
            messages.success9(
                request, 'you have successfully added an event await adminstrator approval', extra_tags='alert')
            return redirect('administrator:view-events')
    else:
        form = EventForm()

    return render(request, 'school/add-event.html', {'form': form})


@login_required(login_url='/administrator/login')
def view_events(request):
    """View all events that have been published."""
    events = Event.objects.filter(event_status='published')
    return render(request, 'school/view-event.html', {'events': events})


class EventUpdate(LoginRequiredMixin, UpdateView):
    form_class = EventForm
    template_name = 'school/add-event.html'
    model = Event

    def get_object(self, *args, **kwargs):
        obj = get_object_or_404(Event, pk=self.kwargs['pk'])
        return obj

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request,
             'Event updated successfully', extra_tags='alert'
        )
        return redirect('administrator:view-events')


def delete_event(request, pk):
    instance = get_object_or_404(Event, pk=pk)
    instance.delete()
    return redirect('administrator:view-events')


# =================================================================================================================================
# Teachers CRUD
# =================================================================================================================================

@login_required(login_url='/administrator/login')
def add_teacher(request):
    """function for adding a single event."""
    if request.method == 'POST':
        form = TeacherForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.save()
            messages.info(
                request, 'you have successfully added a teacher!', extra_tags='alert')
            return redirect('administrator:view-teachers')
    else:
        form = TeacherForm()

    return render(request, 'school/add-teacher.html', {'form': form})


@login_required(login_url='/administrator/login')
def view_teachers(request):
    """View all events that have been published."""
    teacher = Teacher.objects.all()
    return render(request, 'school/view-teachers.html', {'teacher': teacher})


class TeacherUpdate(LoginRequiredMixin, UpdateView):
    form_class = TeacherForm
    template_name = 'school/add-teacher.html'
    model = Event

    def get_object(self, *args, **kwargs):
        obj = get_object_or_404(Teacher, pk=self.kwargs['pk'])
        return obj

    def form_valid(self, form):
        form.save()
        messages.info(
            self.request,
            'Event updated successfully!', extra_tags='alert'
        )
        return redirect('administrator:view-events')


def delete_teacher(request, pk):
    instance = get_object_or_404(Teacher, pk=pk)
    instance.delete()
    return redirect('administrator:view-teachers')

# ==================================================================================================================================
# Executive CRUD
# ==================================================================================================================================

@login_required(login_url='/administrator/login')
def add_executive(request):
    """function for adding a single event."""
    if request.method == 'POST':
        form = ExecutiveForm(request.POST, request.FILES)
        if form.is_valid():
            executive = form.save(commit=False)
            executive.save()
            messages.info(
                request, 'you have successfully added an executive!', extra_tags='alert')
            return redirect('administrator:view-executives')
    else:
        form = ExecutiveForm()

    return render(request, 'school/add-executive.html', {'form': form})


@login_required(login_url='/administrator/login')
def view_executives(request):
    """View all events that have been published."""
    exco = Executive.objects.all()
    return render(request, 'school/view-executives.html', {'exco': exco})


class ExecutiveUpdate(LoginRequiredMixin, UpdateView):
    form_class = ExecutiveForm
    template_name = 'school/add-executive.html'
    model = Executive

    def get_object(self, *args, **kwargs):
        obj = get_object_or_404(Executive, pk=self.kwargs['pk'])
        return obj

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request,
            'Executive updated successfully', extra_tags='alert'
        )
        return redirect('administrator:view-executives')


def delete_executive(request, pk):
    instance = get_object_or_404(Executive, pk=pk)
    instance.delete()
    return redirect('administrator:view-events')

# =================================================================================================================================
# User Profile
# =================================================================================================================================

@login_required(login_url='/administrator/login')
def view_profile(request):
    return render(request, 'school/profile.html')


def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Congratulations your profile was updated successfully!'))
            return redirect('administrator:profile')
        else:
            messages.danger(request, ('Unable to update correct the errors.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'school/profile-update.html', {

administrator/templates/school/add-executive.html
{% extends 'school/form-base.html' %}
{% load staticfiles %}
{% load i18n widget_tweaks %}
{% block title %}Add-Executive {% endblock %}
{% block content %}
<div class="main-content container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default panel-border-color panel-border-color-primary">
          <div class="panel-heading panel-heading-divider">Executive<span class="panel-subtitle"></span></div>
          <div class="panel-body">
              {# error logic #}
              {% for field, errors in form.errors.items %}
              <div class="alert alert-danger alert-dismissible">
              {% for error in errors %}
              <center> <strong>{{ error|escape }}</strong></center>
              {% endfor %}
              </div>
              {% endfor %}

            <form action="#" style="border-radius: 0px;" class="form-horizontal group-border-dashed" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group">
                <label class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                  {% render_field field class='form-control' %}
                </div>
              </div>
                {% endfor %}
              <div class="form-group">
              <p class="text-center">
                  <button type="submit" class="btn btn-space btn-primary btn-lg">Submit</button>
                  {% comment %} <button class="btn btn-space btn-default b">Reset</button> {% endcomment %}
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

  </div>
  </div
  {% endblock %}

administrator/templates/school/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/logo-fav.png">
    <title>{% block title %} {% endblock %} | Aocprivate</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/lib/material-design-icons/css/material-design-iconic-font.min.css' %}"/><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/lib/datatables/css/dataTables.bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/lib/jqvmap/jqvmap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css' %}"/>
    <!-- summernote css -->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/lib/summernote/summernote.css' %}"/>
      <!-- /summernote css -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css"/>


  </head>
  <body>
    <div class="be-wrapper be-fixed-sidebar">
      <nav class="navbar navbar-default navbar-fixed-top be-top-header">
                <div class="container-fluid">
          <div class="navbar-header"><a href="{% url 'administrator:index' %}" class="navbar-brand">be</a>
          </div>
          <div class="be-right-navbar">
            <ul class="nav navbar-nav navbar-right be-user-nav">

              <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">{% if request.user.profile.picture %}<img src="{{ request.user.profile.picture.url }}" alt="Avatar">{% else %}<img src="{% static 'assets/img/avatar.png' %}" alt="Avatar">{% endif %}<span class="user-name">{% if request.user.is_authenticated %}
              {{ request.user.first_name }} {{ request.user.last_name }}
              {% endif %}
              </span></a>
                <ul role="menu" class="dropdown-menu">
                  <li>
                    <div class="user-info">
                      <div class="user-name">{{ request.user.first_name }} {{ request.user.last_name }}</div>
<!--                       <div class="user-position online">Available</div>
 -->                    </div>
                  </li>
                  <li><a href="{% url 'administrator:profile' %}"><span class="icon mdi mdi-face"></span>Profile</a></li>
                  <li><a href="#"><span class="icon mdi mdi-settings"></span> Settings</a></li>
                  <li><a href="{% url 'administrator:logout' %}"><span class="icon mdi mdi-power"></span> Logout</a></li>
                </ul>
              </li>
            </ul>
            <div class="page-title"><span>{% block heading %}Dashboard{% endblock %}</span></div>
            <ul class="nav navbar-nav navbar-right be-icons-nav">
               </span></a>

              </li>

            </ul>
          </div>
        </div>
      </nav>
      <div class="be-left-sidebar">
        <div class="left-sidebar-wrapper"><a href="#" class="left-sidebar-toggle">Dashboard</a>
          <div class="left-sidebar-spacer">
            <div class="left-sidebar-scroll">
              <div class="left-sidebar-content">
                <ul class="sidebar-elements">
                  <li class="divider">Menu</li>
                  <li class="active"><a href="{% url 'administrator:index' %}"><i class="icon mdi mdi-home"></i><span>Dashboard</span></a>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-notifications-active"></i><span>Events</span></a>
                    <ul class="sub-menu">
                      <li><a href="{% url 'administrator:add-event' %}"><i class="icon mdi mdi-file-plus"></i><span> Add Event</span></a>
                      </li>
                      <li><a href="{% url 'administrator:view-events' %}"><i class="icon mdi mdi-folder"></i><span> View Events</span></a>
                      </li>

                    </ul>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-info-outline"></i><span>News</span></a>
                     <ul class="sub-menu">
                      <li><a href="{% url 'administrator:add-news' %}"><i class="icon mdi mdi-file-plus"></i><span> Add News</span></a>
                      </li>
                      <li><a href="{% url 'administrator:view-news' %}"><i class="icon mdi mdi-folder"></i><span> View News</span></a>
                      </li>

                    </ul>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-male-female"></i><span>Teachers</span></a>
                     <ul class="sub-menu">
                      <li><a href="{% url 'administrator:add-teacher' %}"><i class="icon mdi mdi-account-add"></i><span> Add Teacher</span></a>
                      </li>
                      <li><a href="{% url 'administrator:view-teachers' %}"><i class="icon mdi mdi-accounts-alt"></i><span> View Teachers</span></a>
                      </li>

                    </ul>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-case"></i><span>Executives</span></a>
                     <ul class="sub-menu">
                      <li><a href="{% url 'administrator:add-executive' %}"><i class="icon mdi mdi-account-add"></i><span> Add Executive</span></a>
                      </li>
                      <li><a href="{% url 'administrator:view-executives' %}"><i class="icon mdi mdi-accounts-alt"></i><span> View Executives</span></a>
                      </li>

                    </ul>
                  </li>
                  <li class="divider">User</li>

                  <li class=""><a href="{% url 'administrator:profile' %}"><i class="icon mdi mdi-face"></i><span>Profile</span></a>

                  </li>
{#                  <li class=""><a href="#"><i class="icon mdi mdi-settings"></i><span>Settings</span></a>#}
{##}
{#                  </li>#}
                  <li class=""><a href="{% url 'administrator:logout' %}"><i class="icon mdi mdi-power"></i><span>Signout</span></a>

                  </li>

                            </ul>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="be-content">
<!-- block content goes here -->
{% block content %}

{% endblock %}
<!-- block content ends here -->
      </div>

    </div>
    <script src="{% static 'assets/lib/jquery/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/main.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jquery-flot/jquery.flot.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jquery-flot/jquery.flot.pie.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jquery-flot/jquery.flot.resize.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jquery-flot/plugins/jquery.flot.orderBars.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jquery-flot/plugins/curvedLines.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jquery.sparkline/jquery.sparkline.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/countup/countUp.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jqvmap/jquery.vmap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/jqvmap/maps/jquery.vmap.world.js' %}" type="text/javascript"></script>
    <!-- datatables javascript -->

    <script type="text/javascript">
      $(document).ready(function(){
      	//initialize the javascript
      	App.init();
      	App.dashboard();

      });
    </script>
    <script src="{% static 'assets/lib/datatables/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/datatables/js/dataTables.bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/datatables/plugins/buttons/js/dataTables.buttons.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/datatables/plugins/buttons/js/buttons.html5.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/datatables/plugins/buttons/js/buttons.flash.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/datatables/plugins/buttons/js/buttons.print.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/datatables/plugins/buttons/js/buttons.colVis.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/lib/datatables/plugins/buttons/js/buttons.bootstrap.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        //initialize the javascript
        App.init();
        App.dataTables();
      });
    </script>
    <!-- /data-tables javascript -->

  </body>
</html>
<!-- Give respect to hack3r julipels -->

administrator/templates/school/messages.html
{% for message in messages %}
	 <div role="alert" class="alert {{ message.tags }} alert-dismissible">
        <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><span class="icon mdi mdi-check"></span><strong></strong>{{ message }}
    </div>
{% endfor %}

administrator/templates/school/view-event.html
{% extends 'school/view-base.html' %}
{% load staticfiles %}
{% block title %}view-events{% endblock %}
{% block heading %} View Events {% endblock %}
{% block content %}
<div class="main-content container-fluid">
{% include 'school/messages.html' %}
          <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">All Events
                  <div class="tools dropdown"><span class="icon mdi mdi-download"></span><a href="#" type="button" data-toggle="dropdown" class="dropdown-toggle"><span class="icon mdi mdi-more-vert"></span></a>
                    <ul role="menu" class="dropdown-menu pull-right">
                      <li><a href="#">Action</a></li>
                      <li><a href="#">Another action</a></li>
                      <li><a href="#">Something else here</a></li>
                      <li class="divider"></li>
                      <li><a href="#">Separated link</a></li>
                    </ul>
                  </div>
                </div>
                <div class="panel-body table-responsive">
                  <table id="table1" class="table table-striped table-hover table-fw-widget">
                    <thead>
                      <tr>
                        <th>Event Name</th>
                        <th>Date of Event</th>
                        <th>Time of Event</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for events in events %}
                      <tr class="odd gradeX">
                        <td>{{ events.event_title }}</td>
                        <td>
                          {{ events.event_date }}
                        </td>
                        <td>{{ events.event_time }}</td>
                        <td class="center">
                    <div class="btn-group btn-space">
                      <button type="button" class="btn btn-primary">Action</button>
                      <button type="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="mdi mdi-chevron-down"></span><span class="sr-only">Toggle Dropdown</span></button>
                      <ul role="menu" class="dropdown-menu">
                        <li><a href="{% url 'administrator:update-event' pk=events.pk %}">Edit</a></li>
                        <li><a href="{% url 'administrator:delete-event' pk=events.pk %}">Delete</a></li>

                      </ul>
                    </td>
                      </tr>
                      {% endfor %}



                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>


        </div>
      </div>

    </div>

{% endblock %}

administrator/templates/school/view-executives.html
{% extends 'school/view-base.html' %}
{% load staticfiles %}
{% block title %}Adeola {% endblock %}
{% block content %}
<div class="main-content container-fluid">
{% include 'school/messages.html' %}
          <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default panel-table">
                <div class="panel-heading">All News

                </div>
                <div class="panel-body table-responsive">
                  <table id="table1" class="table table-striped table-hover table-fw-widget">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Email</th>
                        <th>Phone</th>
                          <th>Gender</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for exco in exco %}
                      <tr class="odd gradeX">
                        <td>{{ exco.executive_title }} {{ exco.first_name }} {{ exco.last_name }}</td>
                        <td>
                          {{ exco.executive_position }}
                        </td>
                        <td class="center text-info">{{ exco.executive_email }}</td>

                        <td class="center text-success">{{ exco.excutive_phone }}</td>
                        <td>{{ exco.executive_gender }}</td>
                        <td class="center">
                    <div class="btn-group btn-space">
                      <button type="button" class="btn btn-primary">Action</button>
                      <button type="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle"><span class="mdi mdi-chevron-down"></span><span class="sr-only">Toggle Dropdown</span></button>
                      <ul role="menu" class="dropdown-menu">
                        <li><a href="{% url 'administrator:update-executive' pk=exco.pk %}">Edit</a></li>
                        <li><a href="{% url 'administrator:delete-executive' pk=exco.pk %}">Delete</a></li>

                      </ul>
                        </td>

                      </tr>
                      {% endfor %}



                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>


        </div>
      </div>

    </div>

{% endblock %}